version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: fullstack-postgres
    environment:
      POSTGRES_USER: fullstack_user
      POSTGRES_PASSWORD: fullstack_pass
      POSTGRES_DB: fullstack_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres_data: